version: '3.9'

services:
  forgeiq-backend:
    build:
      context: ./apps/forgeiq-backend
    ports:
      - "8000:8000"

  forgeiq-frontend:
    build:
      context: ./apps/forgeiq-frontend
    ports:
      - "8501:8501"
    depends_on:
      - forgeiq-backend
  plan-agent:
    build:
      context: ./agents/PlanAgent
    ports:
      - "8010:8010"
    depends_on:
      - forgeiq-backend
  test-agent:
    build:
      context: ./agents/TestAgent
    ports:
      - "8020:8020"
    depends_on:
      - forgeiq-backend
